name: ${project.name}
main: net.sacredlabyrinth.phaed.dynmap.simpleclans.DynmapSimpleClans
version: ${project.version}
website: ${project.url}
author: phaed
depend: [ dynmap, SimpleClans ]
commands:
  map:
    description: Map commands
    usage: Syntax error, verify the command usage and try again
permissions:
  simpleclans.map.toggle:
    description: Can toggle map visibility